### ISSUE TITLE
No support for range based for loops

### ISSUE THREAD

**Issue by Garados007** [fujidana/vscode-igorpro#16]
If I write the following code, I get an error at the `endfor`:

```igorpro
Function test()
	Make/FREE/N=5 wv = p
	for(variable num : wv)
		print num
	endfor
End
```

This is valid Igor Pro and range based for loops are available since 9.00. More Info:

```igorpro
DisplayHelpTopic "Range-based For-Loop"
```

**Comment by fujidana** [comment]
Thank you for reporting.
Very recently I modified the code (Issue #9) but have not updated the extension at the marketplace.
I am overhauling the syntax parser and plan to publish the new version after that.

**Comment by fujidana** [comment]
Today I published a new version of the extension, `vscode-igorpro` 1.4.0, on the VS Code Marketplace. This version supports the range-based for-loop syntax. I hope this will work fine on your code.

**Comment by Garados007** [comment]
Thanks. This worked.
