### ISSUE TITLE
Wave step size not correctly parsed

### ISSUE THREAD

**Issue by Garados007** [fujidana/vscode-igorpro#19]
Some can use a semicolon `;` to specify the step size in the wave brackets.

```igorpro
Function test()
	Make/FREE wv
	wv[1; 3] = 1
	print wv
End
```

**Comment by fujidana** [comment]
Thanks for reporting it.

I had read "Indexing and Subranges" help page (`DisplayHelpTopics "Indexing and Subranges"`) during writing the parser code and knew that the starting and ending index can be omitted (e.g., `wv[,; 3]`, `wv[1,; 3]`, but didn't know a comma can be also omitted.

I will add a syntax rule for this.

**Comment by fujidana** [comment]
Before modifying the code, I studied sub-range rules a little. Here I make a note about it, for future reference (to me).

The following expressions are allowed:

```igorpro
// single-element access
wv[ind]
// subrange access
wv[] // full range
wv[start,end] // range from `start` to `end`
wv[start,end;increment] // range from `start` to `end` by `increment` step
wv[start;increment] // range from `start` to end of wave by `increment` step
```

Several parameters can be omitted. The rule about omission looks as follows:

- In any cases that explicitly use `;`, `increment` cannot be omitted.
- In any cases, `start` can be omitted. If omitted, `0` is the implicit value of `start`. (but in case of `wv[ind]` and `wv[]`, the meanings become different)
- In any cases, `end` can be omitted. If omitted, `numpnt(wv) - 1` or `Inf` is the implicit value of `end`.
- `*` can be used for `end` but cannot be used for `start` or `increment`. Using `*` is equivalent with omission of `end`, i.e., indicating end of the wave index. There are two exceptions to this rule, as shown below. In these cases I think `*` means _full range_:
  - `wv[*]`: equivalent with `wv[]`, not with `wv[0]`
  - `wv[*;increment]`: equivalent with `wv[;increment]` and `wv[0;increment]` 

Hmm, I feel here the grammar of Igor Pro is not very consistent.

**Comment by fujidana** [comment]
I published a fixed version.
