### ISSUE TITLE
Access of static functions inside independent modules

### ISSUE THREAD

**Issue by Garados007** [fujidana/vscode-igorpro#20]
I found another bug in your grammar, which I want to report. Static functions inside independent modules are accessed using 

```igorpro
IndependentModuleName#RegularModuleName#FunctionName()
```
More information:

```igorpro
DisplayHelpTopic "Regular Modules Within Independent Modules"
```

**Comment by fujidana** [comment]
Thank you for reporting!

The current parser only allows one `#` in a function callee. I have used static function a few times but haven't used independent module, and so I didn't imagine the case `#` appears twice.

I will fix the parser soon.

**Comment by fujidana** [comment]
I published a fixed version on the marketplace.

It looks Igor Pro's compiler does not complain if additional spaces exist around '#' (and also before the parenthesis) in a function call, while built-in editor doesn't colorize them properly. That is the same as GitHub's syntax highlighter for Igor Pro language.

My extension was modified to support a case that additional spaces are included, while such a coding style will be not recommended.

```igorpro
IndependentModuleName#RegularModuleName#FunctionName()
FuncionName()

IndependentModuleName # RegularModuleName # FunctionName ()
FuncionName ()

**Comment by Garados007** [comment]
I created an issue to get this fixed at Github: https://github.com/byte-physics/language-igor/issues/30
