### ISSUE TITLE
Optional arguments are not correctly parsed

### ISSUE THREAD

**Issue by Garados007** [fujidana/vscode-igorpro#5]
I just updated your extension and I have seen that a lot of my code is now highlighted as an error. One of them is this:

```igorpro
Function FuncWithOptional(string a, [value b])
End

Function Call()
    FuncWithOptional("a", b = 1) // this line is highlighted as error
End
```

This is valid Igor Pro code and used in many of our projects.

**Comment by fujidana** [comment]
Thank you for reporting the problem.
The syntax parser did not consider cases of optional parameters.

I just fixed some codes and published a pre-release version of the extension (`fujidana.vscode-igorpro` 1.3.1) on the marketplace. Also, I put the fixed code on this repository (then, I miss to link this issue with the commit).

**Comment by Garados007** [comment]
> I miss to link this issue with the commit

No problem. The commit is 58eb70e1b84399cd2a186ea832ee6f8aa8a74321

**Comment by Garados007** [comment]
> I just fixed some codes and published a pre-release version of the extension (fujidana.vscode-igorpro 1.3.1) on the marketplace. 

I just tried the pre release version. Seems to be working for me. Thanks for the quick fix.
