### ISSUE TITLE
Obsolete operator style not supported

### ISSUE THREAD

**Issue by Garados007** [fujidana/vscode-igorpro#6]
Igor Pro has a bunch of obsolete operators that should not be used in new Igor code but unfortunate is still contained in old one. I am speaking of

- `%~`: old style bitwise complement
- `%&`: old style bitwise and
- `%|`: old style bitwise or

More information can be seen with: `DisplayHelpTopic "Obsolete Operators"`

**Comment by fujidana** [comment]
Thank you for reporting the problem.
While the syntax highlighting code has been supported these obsolete operators (they are tokenized as `invalid.deprecated` and in most color theme they are colored red), the syntax parser code has missed out support to them.
I will try to fix it.

**Comment by fujidana** [comment]
According to the Igor Pro help doc, WaveMetrics does not recommend to replace old bit-wise operators in old code with new ones. So, I decided that the parser will diagnose these operators as information-level problems, not warning-level.
(Diagnostic severity of VS Code has 4 levels. See https://code.visualstudio.com/api/references/vscode-api#DiagnosticSeverity)
<img width="838" alt="screenshot_deprecated_bitwise_operator" src="https://github.com/user-attachments/assets/e592b1f2-c68f-40d6-90ba-c3b86cd8690e">
